---
- name: Deploy WordPress to /srv/www
  hosts: webserver
  become: yes

  tasks:
    - name: Ensure /srv/www exists
      file:
        path: /srv/www
        state: directory
        owner: www-data
        group: www-data
        mode: '0777'

    - name: Download latest WordPress archive
      get_url:
        url: https://wordpress.org/latest.tar.gz
        dest: /tmp/wordpress.tar.gz
        mode: '0644'

    - name: Extract WordPress to /srv/www as www-data
      become_user: root
      unarchive:
        src: /tmp/wordpress.tar.gz
        dest: /srv/www
        remote_src: yes
